{{- if or (and .Values.adminPassword (not .Values.existingSecret)) (and .Values.uptimy.heartbeatUrl (not .Values.uptimy.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptimy-agent.fullname" . }}
  labels: {{- include "uptimy-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.adminPassword (not .Values.existingSecret) }}
  ADMIN_PASSWORD: {{ .Values.adminPassword | quote }}
  {{- end }}
  {{- if and .Values.uptimy.heartbeatUrl (not .Values.uptimy.existingSecret) }}
  UPTIMY_HEARTBEAT_URL: {{ .Values.uptimy.heartbeatUrl | quote }}
  {{- end }}
{{- end }}
